-- ============================================
-- Create Project Table
-- ============================================
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- ============================================
-- Create Task Table
-- ============================================
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    priority INTEGER NOT NULL CHECK (priority >= 1 AND priority <= 5),
    due_date DATE NOT NULL,
    assignee VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    project_id BIGINT NOT NULL,
    version BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE
);

-- ============================================
-- Create Indexes for Performance
-- ============================================
CREATE INDEX idx_project_id ON task(project_id);
CREATE INDEX idx_due_date ON task(due_date);
CREATE INDEX idx_priority ON task(priority);
CREATE INDEX idx_status ON task(status);
